RDKCOM-3556: RDKBDEV-1518: use correct names to access source and dest
Reason for change:
dmltad: use correct names to access source and dest ports in struct udphdr
'source' and 'dest' are aliases and may not always be defined.
 | In file included from ../../../git/source/dmltad/cosa_wanconnectivity_operations.h:40,
 |                  from ../../../git/source/dmltad/cosa_wanconnectivity_operations.c:22:
 | ../../../git/source/dmltad/cosa_wanconnectivity_operations.c: In function 'get_dns_payload':
 | ../../../git/source/dmltad/cosa_wanconnectivity_operations.c:1423:65: error: 'struct udphdr' has no member named 'source'
 |  1423 |                                                 ntohs(udp_header->source), ntohs(udp_header->dest));
 |       |                                                                 ^~
 | ../../../git/source/dmltad/cosa_wanconnectivity_operations.c:1423:92: error: 'struct udphdr' has no member named 'dest'
 |  1423 |                                                 ntohs(udp_header->source), ntohs(udp_header->dest));
 |       |                                                                                            ^~
Test Procedure: Build and Sanity.
Risks: None.
Signed-off-by: Andre McCurdy <armccurdy@gmail.com>

(cherry picked from commit 1392130aaead1d1720d3f3a69b1ea47f0928b867)
Change-Id: Ib520a7ee50abcb49b487e950053b155913cfa7a9